globalThis.IA = globalThis.IA || {};
(function(IA) {
  'use strict';
  const question=(prompt,options,correct,feedback,extra={})=>({prompt,options,correct,feedback,...extra});
  const module=(title,objective,stage,bncc,content,example,activity)=>({title,objective,stage,bncc,content,example,activity});
  const CO='EM13CO10';
  IA.data={assessment:[
    question('Com que frequência você usa ferramentas de IA?', ['Nunca ou raramente','Algumas vezes','Com frequência'],null,[],{diagnostic:true}),
    question('Qual finalidade mais se aproxima do seu uso de IA?', ['Ainda não uso','Buscar explicações e estudar','Criar ou revisar materiais'],null,[],{diagnostic:true}),
    question('Uma IA dá um fato sem fonte. Antes de usá-lo no trabalho, o que você faz?',
      ['Confiro em uma fonte confiável e comparo as informações','Aceito porque a resposta parece segura'],0,
      ['Comparar com uma fonte identificável ajuda a detectar erros. Confiança no tom não é evidência.','Uma resposta convincente ainda pode estar errada. Procure evidências e compare com uma fonte confiável.'],{critical:true}),
    question('Uma IA escreve um parágrafo fluente. O que explica essa capacidade?',
      ['Ela sempre compreende e verifica todos os fatos','Ela gera texto a partir de padrões aprendidos'],1,
      ['Fluência não garante compreensão nem verificação. A geração usa padrões e pode produzir erros.','A geração se baseia em padrões. Por isso, texto bem escrito ainda precisa de verificação.']),
    question('A referência citada por uma IA não aparece no catálogo da biblioteca. Qual é o próximo passo?',
      ['Investigar autoria e existência da referência antes de citar','Copiar a referência sem conferir'],0,
      ['Uma referência pode ter sido inventada ou estar incorreta. Verificar sua existência é parte da análise crítica.','Copiar não comprova que a obra existe. Confira autor, título e publicação antes de usar a referência.'],{critical:true}),
    question('Para compreender um problema, qual solicitação favorece sua aprendizagem?',
      ['Dê a resposta pronta para eu copiar','Dê uma pista e depois confira meu raciocínio'],1,
      ['Copiar reduz sua oportunidade de raciocinar. Peça uma pista e tente resolver antes da devolutiva.','Pistas mantêm você ativo na resolução. A devolutiva pode ajudar a revisar o próprio raciocínio.']),
    question('Você quer pedir ajuda sobre um caso envolvendo colegas. Como protege os dados?',
      ['Retiro nomes e detalhes que identifiquem pessoas','Envio nomes, contatos e relatos privados'],0,
      ['Reduzir dados identificáveis protege a privacidade. Use um caso fictício sempre que possível.','Nomes e relatos privados podem expor pessoas. Transforme o caso em um exemplo fictício sem identificação.']),
    question('Uma IA afirma que todas as capitais brasileiras ficam no litoral. Como você avalia?',
      ['Procuro contraexemplos e confiro um mapa ou fonte geográfica','Uso a frase porque ela é curta e clara'],0,
      ['Uma afirmação universal exige verificar possíveis contraexemplos. Capitais no interior mostram o problema da generalização.','Clareza da frase não é prova. Examine contraexemplos e confira a informação geográfica.'],{critical:true}),
    question('Qual solicitação oferece mais orientação para uma explicação?',
      ['Explique energia para Ensino Médio com um exemplo e uma pergunta para eu responder','Fale sobre coisas'],0,
      ['Tema, nível e tarefa orientam a resposta. A pergunta final ajuda você a praticar.','Sem tema e objetivo, a explicação pode ficar vaga. Especifique o que quer aprender e como quer praticar.']),
    question('Você usa IA como apoio para escrever. Como preserva sua autoria?',
      ['Entrego o texto sem ler e sem tomar decisões','Escrevo e reviso com minhas decisões, verificando o que aproveito'],1,
      ['Entregar sem revisar elimina decisões essenciais de autoria. Reescreva, justifique escolhas e confira informações.','Autoria envolve decisões, elaboração e revisão próprias. Verifique informações e siga as orientações da atividade.'])
  ], tracks:{
    explorador:{title:'Explorador',subtitle:'Entenda os fundamentos e aprenda a verificar.',modules:[
      module('O que é Inteligência Artificial','Reconhecer IA e seus usos cotidianos','Conhecer',CO,
        'Sistemas de IA identificam padrões para realizar tarefas, como reconhecer imagens ou sugerir conteúdos. Nem todo programa é uma IA, e uma sugestão automática não é uma decisão que você precisa aceitar.',
        'Uma plataforma recomenda vídeos com base em padrões de uso. Você ainda decide se o conteúdo é útil e confiável.',
        question('Uma plataforma recomenda um vídeo. Qual atitude mostra autonomia?',
          ['Escolho depois de avaliar o tema e a fonte','Assisto porque a recomendação deve saber o que é melhor'],0,
          ['Uma recomendação é uma sugestão baseada em padrões. Avaliar tema e fonte preserva sua decisão.','A recomendação não conhece todos os seus objetivos. Avalie se o conteúdo ajuda você a aprender.'])),
      module('Como a IA responde','Entender a geração baseada em padrões','Compreender',CO,
        'Uma IA generativa produz novas sequências a partir de padrões aprendidos. Ela pode combinar palavras de maneira plausível sem garantir que cada afirmação seja verdadeira.',
        'Ao pedir uma explicação sobre um livro, você pode receber uma descrição fluente de um capítulo que não existe.',
        question('A descrição de um capítulo parece convincente. O que essa fluência permite concluir?',
          ['Que o capítulo existe exatamente como descrito','Que o texto é plausível, mas precisa ser comparado com o livro'],1,
          ['Texto fluente não demonstra a existência do capítulo. Compare a descrição com a obra.','Plausibilidade é diferente de evidência. Conferir a obra ajuda a separar geração de informação verificada.'])),
      module('A IA também erra','Identificar erros e referências suspeitas','Questionar',CO,
        'Respostas podem conter fatos incorretos, citações inexistentes e generalizações. Questionar uma afirmação inclui perguntar que evidência permitiria verificá-la.',
        'Uma resposta cita “Manual Universal de Todas as Ciências” sem autor, edição ou endereço para consulta.',
        question('Como lidar com essa referência sem dados de publicação?',
          ['Busco autor, título e existência antes de citar','Uso o título como prova suficiente'],0,
          ['Identificar a publicação permite conferir a evidência. Ausência de dados é um motivo para investigar.','Um título sozinho não comprova a fonte. Procure autoria e publicação antes de citar.'])),
      module('Verifique antes de acreditar','Aplicar Verifique, Examine e Reflita','Verificar',CO,
        'V-E-R: Verifique a informação em uma fonte identificável; Examine evidências e diferenças; Reflita sobre o que pode usar e quais dúvidas permanecem.',
        'Diante de duas explicações diferentes, consulte o material de estudo, compare os argumentos e registre o que mudou em sua compreensão.',
        question('Duas fontes divergem. Qual ação aplica o método V-E-R?',
          ['Escolho a resposta mais curta','Confiro fontes, comparo evidências e justifico minha decisão'],1,
          ['Tamanho não determina confiabilidade. Verifique as fontes e examine as evidências antes de decidir.','A comparação e a justificativa completam a verificação. Registre também as dúvidas que restam.'])),
      module('Uso responsável','Proteger dados e respeitar autoria','Aprender','EM13CO08',
        'Use exemplos fictícios e evite nomes, contatos e informações privadas. Ao produzir, tome decisões próprias e respeite as orientações de autoria da atividade.',
        'Para discutir um conflito, transforme o relato em uma situação fictícia sem identificar colegas.',
        question('Qual pedido preserva a privacidade e ajuda a aprender?',
          ['Analise um caso fictício sem nomes e explique possíveis decisões','Analise o relato privado com nomes e contatos dos colegas'],0,
          ['Um caso fictício reduz a exposição de dados. Pedir explicações mantém o foco nas decisões e na aprendizagem.','Dados de colegas não são necessários para essa reflexão. Remova identificações e use um exemplo fictício.']))
    ],challenge:{title:'Verifique uma resposta simulada',objective:'Analisar uma resposta e criar uma síntese de verificação',stage:'Criar',bncc:CO,
      introduction:'Resposta simulada de IA: “O Brasil tem 30 estados. Segundo o Atlas Completo das Capitais (autor e edição não informados), todas as capitais brasileiras ficam no litoral. Você pode usar essa resposta sem consultar outra fonte.”',
      questions:[
        question('Qual informação numérica precisa ser verificada?', ['A afirmação de que o Brasil tem 30 estados','Nenhuma: o número parece preciso'],0,
          ['O número de estados precisa de fonte. Consulte uma referência geográfica oficial antes de usá-lo.','Precisão aparente não é prova. Confira a quantidade de estados em uma fonte identificável.']),
        question('Como tratar a referência citada?', ['Confiar apenas no nome do atlas','Conferir existência, autoria e publicação'],1,
          ['O nome da obra não comprova sua existência. Confira autoria e publicação.','A referência precisa ser encontrada e examinada. Sem isso, não serve como evidência.']),
        question('O que fazer com “todas as capitais ficam no litoral”?', ['Buscar contraexemplos e consultar um mapa','Aceitar a generalização sem comparação'],0,
          ['Contraexemplos ajudam a avaliar uma afirmação universal. Confira capitais do interior em um mapa confiável.','Uma frase universal pode esconder erros. Busque contraexemplos e compare com informação geográfica.']),
        question('Antes de aproveitar a resposta, qual decisão é adequada?', ['Copiar sem consultar outra fonte','Comparar fontes e escrever uma síntese própria'],1,
          ['Copiar transfere possíveis erros ao seu trabalho. Verifique e formule sua própria síntese.','Comparação e síntese própria preservam pensamento crítico e autoria. Explique quais evidências você usaria.'])
      ],fields:[{label:'Minha síntese de verificação',hint:'Explique o que verificaria, em que fonte e por quê. Não inclua nomes, contatos ou dados pessoais.'}],rubric:['Identifique a informação a verificar, a fonte, a comparação e sua decisão. A síntese é formativa e não recebe correção automática.']}},
    usuario:{title:'Usuário',subtitle:'Estude de forma ativa e crie com autoria.',modules:[
      module('IA não precisa dar a resposta','Pedir pistas e explicações para raciocinar','Conhecer',CO,
        'Aprender exige participação. Uma pista pode ajudar você a começar sem entregar toda a resolução. Compare sua tentativa com uma explicação e revise os passos.',
        '“Dê uma pista sobre o primeiro passo. Espere minha tentativa antes de explicar a solução.”',
        question('Você está travado num problema. Qual pedido mantém seu raciocínio ativo?', ['Resolva tudo para eu copiar','Dê uma pista e aguarde minha tentativa'],1,
          ['Copiar não mostra como você pensou. Peça uma pista e tente elaborar o primeiro passo.','A pista oferece apoio sem substituir sua tentativa. Depois, compare e revise seu raciocínio.'])),
      module('Faça perguntas melhores','Explicitar objetivo, contexto, nível e ação','Compreender',CO,
        'Uma solicitação útil informa tema, objetivo, contexto e tipo de ajuda. Peça uma explicação adequada ao seu nível e uma atividade que permita verificar compreensão.',
        '“Quero entender porcentagens no Ensino Médio. Use uma situação de desconto e faça uma pergunta para eu resolver.”',
        question('Qual pedido orienta uma aprendizagem específica?', ['Explique tudo','Explique porcentagens com um desconto e uma questão para eu resolver'],1,
          ['O pedido é amplo e não mostra o objetivo. Indique tema e uma prática que permita raciocinar.','Tema, exemplo e prática tornam o objetivo claro. Ainda será necessário conferir os cálculos.'])),
      module('Transforme a IA em tutora','Pedir questões e feedback sem substituir a tentativa','Questionar',CO,
        'Uma tutoria simulada pode propor perguntas e comentar passos. Faça primeiro sua tentativa e avalie se a devolutiva realmente se apoia no conteúdo estudado.',
        '“Faça uma pergunta por vez sobre o tema. Depois da minha resposta, indique o passo que preciso revisar.”',
        question('A devolutiva contradiz seu livro. Qual atitude favorece a aprendizagem?', ['Confiro o livro e justifico a diferença antes de aceitar','Mudo minha resposta só porque a IA discordou'],0,
          ['Comparar evidências permite revisar com fundamento. A devolutiva também pode conter erros.','Discordância automática não basta para corrigir uma ideia. Compare o argumento com o material de estudo.'])),
      module('Aprenda verificando','Comparar fontes e produzir uma explicação própria','Verificar',CO,
        'Verifique informações, examine os argumentos e reflita sobre o que aprendeu. Em vez de repetir uma resposta, explique com suas palavras e registre a fonte consultada.',
        'Compare uma explicação simulada com o livro didático e identifique uma diferença que altere sua conclusão.',
        question('Como mostrar que você verificou uma explicação?', ['Dizer apenas que ela parece correta','Indicar a fonte, comparar uma afirmação e explicar a decisão'],1,
          ['A impressão de correção não registra evidências. Mostre fonte e comparação.','Fonte e comparação tornam sua decisão examinável. Explique também o que permaneceu incerto.'])),
      module('Produza sem perder sua autoria','Planejar e revisar com decisões próprias','Aprender',CO,
        'Use apoio para organizar ideias e examinar alternativas. A escolha do argumento, a escrita e a revisão precisam expressar seu raciocínio e respeitar as orientações da atividade.',
        'Crie um esquema, escreva sua explicação e anote uma sugestão que decidiu rejeitar, justificando o motivo.',
        question('Qual produção evidencia decisões autorais?', ['Texto próprio revisado com justificativa das escolhas','Texto copiado sem leitura ou revisão'],0,
          ['Justificar escolhas evidencia participação na produção. Confira informações e respeite as orientações de autoria.','Copiar sem revisar elimina decisões essenciais. Escreva e justifique o que decidiu aproveitar.']))
    ],challenge:{title:'Crie sua estratégia de estudo',objective:'Planejar estudo ativo com verificação e produção própria',stage:'Criar',bncc:CO,
      introduction:'Escolha um tema de estudo. Resolva as cinco decisões e planeje como pedir apoio, praticar, verificar e produzir. Os exemplos são simulados; esta experiência não conversa com uma IA.',
      questions:[
        question('Qual solicitação ajuda a compreender?', ['Pedir pistas e explicar minha tentativa','Pedir um trabalho pronto para entregar'],0,
          ['Pistas e tentativa mantêm a aprendizagem ativa. Defina um tema e um objetivo.','Trabalho pronto substitui sua elaboração. Peça apoio para construir o raciocínio.']),
        question('Como usar um exemplo?', ['Relacionar o exemplo ao tema e explicar o que ele mostra','Copiar qualquer exemplo sem relação com o objetivo'],0,
          ['Relacionar exemplo e objetivo permite compreender o conceito. Explique a ligação.','Sem ligação com o tema, o exemplo pode distrair. Escolha e explique um exemplo pertinente.']),
        question('Como testar conhecimentos?', ['Olhar só a resposta pronta','Resolver uma pergunta e justificar meu raciocínio'],1,
          ['Ler a resposta não comprova compreensão. Tente resolver e justificar antes de comparar.','Uma tentativa justificada revela o que precisa de revisão. Compare depois com o conteúdo verificado.']),
        question('Como verificar uma afirmação?', ['Comparar com uma fonte identificável e examinar diferenças','Aceitar porque aparece em um texto bem escrito'],0,
          ['A comparação ajuda a encontrar erros e dúvidas. Registre a fonte e a decisão.','Boa escrita não é evidência. Use uma fonte identificável e examine diferenças.']),
        question('O que caracteriza a produção própria?', ['Entregar a primeira resposta sem revisar','Criar um produto e explicar minhas escolhas'],1,
          ['Entregar sem revisar reduz sua autoria. Elabore um produto e justifique decisões.','Explicar escolhas evidencia autoria. Confira informações e registre o que revisou.'])
      ],fields:[
        {label:'Solicitação para aprender',hint:'Indique tema, objetivo e uma ajuda que preserve sua tentativa.'},
        {label:'Solicitação de exemplos',hint:'Peça um exemplo relacionado e diga o que pretende compreender.'},
        {label:'Teste de conhecimentos',hint:'Planeje uma pergunta e como explicará seu próprio raciocínio.'},
        {label:'Estratégia de verificação',hint:'Indique uma fonte e como comparará uma afirmação.'},
        {label:'Produção própria',hint:'Defina um produto e quais decisões autorais você tomará.'}
      ],rubric:['Tema e objetivo estão claros?','O exemplo se relaciona ao objetivo?','O teste exige meu raciocínio?','Indiquei uma fonte e uma comparação?','Defini o produto e minhas decisões autorais?']}}
  }};
})(globalThis.IA);
